Stop early if randomize_stat_freqs won't do anything
zopfli-rs/zopfli pull request #22
Opened 2023-06-24 23:51 UTC by Pr0methean

`randomize_stat_freqs` can't have any effect in the case where all the symbols in `beststats` have the same frequency, nor does `lz77_optimal` have any way to improve the compression if that's the case and the last iteration had no effect. So this PR ends the deflation of the block early if that happens.

2023-06-26 21:02 UTC, AlexTMjugador requested changes
Thank you a bunch for the PR, and sorry it took me a while to get to review it! The ideas behind the changes are sensible.

However, in its current implementation, it causes an overall slight regression in the compressed size of the test files:

![CI output](https://github.com/zopfli-rs/zopfli/assets/7822554/d64f23ce-1ba5-4695-a16a-f77ebab3b6f7)

This shows that while there is indeed no point in randomizing frequencies under the conditions you describe, it's not true that further LZ77 runs are "redundant" if there is nothing to randomize at a given iteration. It's debatable whether the performance gains (according to your rollup PR, when used with #21, 52m 7s vs. 53m9s) are worth the small compression losses (148 bytes in your test), but the point of Zopfli is to generate near-optimal DEFLATE streams, so I think that at least this kind of early-stopping behavior that might cause compression regressions should be made optional.

Would you mind making this and other potentially risky behavior changes toggleable? :smile:

2023-06-27 02:18 UTC, Pr0methean commented
Have you confirmed with Trace-level logging that the further LZ77 runs are making the difference, and not just the slightly different PRNG state from having been invoked fewer times?

2023-06-27 10:07 UTC, AlexTMjugador commented
I didn't check whether the root cause for the regressions was the different PRNG state or the fact that less LZ77 runs are done, but our results show that even if the cause is a different PRNG state, on average it's slightly worse, and thus the behavior change is a good candidate to be toggleable.

2023-06-27 11:39 UTC, Pr0methean commented
It seems like the optimality is very sensitive to the PRNG state. (Compare the last two commits on eeyore.png!) I think instead of trying to micro-optimize Zopfli, I'll fork it and experiment with other methods of optimizing `stats` such as genetic algorithms.

2023-06-27 11:39 UTC, closed without merging